### ISSUE TITLE
Check if an env already exists in `env add`

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#115]
Currently, we don't check to see if an environment already exists when we're adding a new env. It's not wrong, but it just means we show the deployment fast succeed message and then the error that the env already exists.

Current:
```
 archer env add test --project dave
Done!
Error: environment test already exists in project dave
```

Wanted:

```
 archer env add test --project dave
Error: environment test already exists in project dave
```

**Comment by ganeshmannamal** [comment]
hello @kohidave I would love to contribute to this issue

**Comment by ganeshmannamal** [comment]
@kohidave cmiiw its `env init test --project dave`(int not add)?

**Comment by efekarakus** [comment]
@ganeshmannamal Thanks for looking into this! You're right :) it's `env init` and not `env add`
 
Unfortunately, I think this is a stale issue :( we do return immediately in `env init` if the environment already exists:
https://github.com/aws/amazon-ecs-cli-v2/blob/12976618b6862969be7a20463ee4591e74458585/internal/pkg/cli/env_init.go#L91-L98

with the message:
"✔ Success! Environment {env} already exists under project {project}! Do nothing."

I believe this is a better user experience (succeeding instead of failing) if the env already exists.

I'll close the issue.

**Comment by ganeshmannamal** [comment]
@efekarakus yes just realised this while reading the code 🖖
