### ISSUE TITLE
Generated buildspec failed in the pipeline Build stage

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#417]
I saw this in the Build stage in the archer pipeline:
```
[Container] 2019/11/19 23:16:56 Running command for env in $envs; do 
  for app in $apps; do 
  ./archer app package -n $app -e $env --output-dir './infrastructure' --tag $tag; 
  done; 
done; 
 
Error: get environment (prod) in project archer-sample-project: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_ 
    status code: 400, request id: 87205e5b-f26f-4521-8ff6-d5708afdc59f 
```

**Comment by hencrice** [comment]
[buildspec.yml.zip](https://github.com/aws/amazon-ecs-cli-v2/files/3866545/buildspec.yml.zip)

**Comment by hencrice** [comment]
The environment names are:
`fake-prod-env (prod)`, `test-env`. Discussed offline with Efe and seems like `fake-prod-env (prod)` is the issue here.

**Comment by efekarakus** [comment]
This is because the envs are retrieved with:
https://github.com/aws/amazon-ecs-cli-v2/blob/4dbdd4f89a601d7c1c16566f49af387360395a7f/templates/cicd/buildspec.yml#L40 

If the environment is a production environment, then the name retrieved is like `"prod-us-west-1 (prod)"`

The additional ` (prod)` breaks the script.

My proposal to fix this issue is to add a `--json` flag to the `env ls` command. This way we can use jq to retrieve only the environment name.

**Comment by efekarakus** [comment]
I'll pick this up
