### ISSUE TITLE
[Windows/PowerShell] `init` msgs print out in sequence vs. showing rotating status symbol

### ISSUE THREAD

**Issue by allisaurus** [aws/amazon-ecs-cli-v2#435]
When running `init` the status msgs print on a new line each time instead of appearing as a stationary line with a rotating status symbol on the left. Suspicion is this might be related to color use, but the success msg uses and successfully shows colors. See image.

![toomanymsgs](https://user-images.githubusercontent.com/34254888/69267364-d75b6800-0b81-11ea-8d74-b6a3418a5b98.PNG)

**Comment by efekarakus** [comment]
I'll pick this up

**Comment by efekarakus** [comment]
### Observation
1. As was mentioned by @sonofachamp and @allisaurus, the ANSI sequences are appearing in the **spinner's** text instead of real colors. We know that the shell supports the basic 16 colors as we can see it in the next line with a green "√ Success!"

### Hypothesis
The unrendered sequences causes the cursor to not pick the correct line resulting in this series of messages.
It looks like this is because the spinner uses the default `os.Stderr` which won't work for windows:
https://github.com/aws/amazon-ecs-cli-v2/blob/88ee4845aef27cafb08860c5b0d8b0d652c9da80/internal/pkg/term/progress/spinner.go#L62

Instead of leveraging, the `DiagnosticWriter` which will work for Windows:
https://github.com/aws/amazon-ecs-cli-v2/blob/88ee4845aef27cafb08860c5b0d8b0d652c9da80/internal/pkg/term/log/log.go#L23

**Comment by efekarakus** [comment]
After implementing the changes above, the color appears in the spinner but the line is not erased yet:
![Screen Shot 2019-11-20 at 5 23 36 PM](https://user-images.githubusercontent.com/879348/69292320-a8adb380-0bba-11ea-9ae8-7ae1a000b600.png)

**Comment by efekarakus** [comment]
Upgraded to spinnerv1.8.0 and it's fixed!
![Screen Shot 2019-11-21 at 10 18 02 AM](https://user-images.githubusercontent.com/879348/69365168-95e1c000-0c48-11ea-8089-8654b5d1f71f.png)

We made a contribution to fix this issue :D https://github.com/briandowns/spinner/pull/84
