### ISSUE TITLE
Bug Bash Feedback: archer init

### ISSUE THREAD

**Issue by pkandasamy91** [aws/amazon-ecs-cli-v2#436]
Running archer init - after the environments are created it asks me about which app I want to use, I only created efesafe, but it seems to have an api app as well.

<img width="568" alt="Screen Shot 2019-11-20 at 10 39 13 AM" src="https://user-images.githubusercontent.com/44981951/69267491-17bae600-0b82-11ea-9efc-ed8f947d2914.png">

**Comment by efekarakus** [comment]
I'll pick this up.

**Comment by efekarakus** [comment]
I can reproduce the bug 
![bug](https://user-images.githubusercontent.com/879348/69286506-4d72c580-0ba8-11ea-9313-3b5f7d2380df.png)


If the `"test"` environment already exists and we choose deploy the application then this prompt shows up. 

The expected behavior would have been to deploy the "backend" application instead of this prompt showing up.
