### ISSUE TITLE
Pipeline update can't complete if trying to update an unchanged pipeline

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#465]
Stuck at `Proposing infrastructure changes for the pipeline` when trying to deploy an unchanged pipeline.

However, it won't get stuck if the pipeline already got updated with a change and then do an update with no change.

**Comment by sonofachamp** [comment]
It's hanging on this call:
https://github.com/aws/amazon-ecs-cli-v2/blob/8cece1f99dbb2ff33869741789d2846edda76089/internal/pkg/deploy/cloudformation/pipeline.go#L45-L48

because the ChangetSet fails, we delete it, and the Acceptors in the [SDK function call](https://github.com/aws/aws-sdk-go/blob/ca01a573c9b8f7622c3f955c094a5d6a9927bfa8/service/cloudformation/waiters.go#L368-L398) are looking for one of:
* `UPDATE_COMPLETE`
* `UPDATE_FAILED`
* `UPDATE_ROLLBACK_FAILED`
* `UPDATE_ROLLBACK_COMPLETE`
* `ValidationError`
