### ISSUE TITLE
Best practices for removing an env?

### ISSUE THREAD

**Issue by stevelizcano** [aws/amazon-ecs-cli-v2#811]
I spawned three envs, and needed to trim one down to get to staging + prod. 

I had already added my app, and could not remove the Env without removing the App first...which promptly removed the App from all three of my env's. 

Is there a way to remove an env without having to remove an app, therefore preventing the cascade to all other Envs?

**Comment by efekarakus** [comment]
Hi @stevelizcano !

There isn't a way of removing an environment without deleting applications in it at the moment. 

However, we do provide a way of removing an application from a single environment instead of all of them: `ecs-preview app delete --env {name}`.
This will remove it from the `{name}` environment and not the other ones, then you can delete the environment with `ecs-preview env delete` successfully.

**Comment by stevelizcano** [comment]
Perfect, thanks for the info! I really liked your webinar a few days back!
